### ISSUE TITLE
Broken image link in https://docs.hydra.so/organize/data-modeling/recommended-schema

### ISSUE THREAD

**Issue by saputradharma** [hydradatabase/docs#37]
Link to [image](https://hydras.io/assets/blog/2022-10-19/star-schema-6902bc4b4b608aad3844912e49028d73a2a99e4d629fbe0cf018f68b60d9a37d.png) seems broken in this [docs](https://docs.hydra.so/organize/data-modeling/recommended-schema) page

**Comment by wuputah** [comment]
thanks for noticing and reporting the issue!
